app/views/layouts/application.html.erb, config/locales/en.yml
@benlovell @jongilbraith
Add placeholder content for the title_tag and the meta_tag. Content from Mo in the "SEO department".
=> Add title tag and meta tag to the layout

app/assets/stylesheets/_enhanced.scss, app/assets/stylesheets/components/further_info/_further_info.scss, app/assets/stylesheets/components/search/_all.scss, app/assets/stylesheets/components/search/_search.scss, app/assets/stylesheets/components/search/_settings.scss, app/assets/stylesheets/layouts/_landing_page.scss, app/controllers/landing_page_controller.rb, app/forms/search_form.rb, app/views/landing_page/_search_filter.html.erb, app/views/landing_page/_search_filter_options.html.erb, app/views/landing_page/show.html.erb, config/application.rb, config/locales/en.yml
=> 5777 Part one of the search filter module

app/assets/stylesheets/_enhanced.scss, app/assets/stylesheets/components/beta_tag/_all.scss, app/assets/stylesheets/components/beta_tag/_beta_tag.scss, app/assets/stylesheets/components/beta_tag/_settings.scss, app/views/landing_page/show.html.erb, config/locales/en.yml
@moneyadviceservice/frontend @benlovell
=> Add beta tag component to the landing page

app/assets/stylesheets/layouts/_landing_page.scss, app/views/landing_page/_search_filter.html.erb, app/views/layouts/application.html.erb
=> Reposition the validation summary after DAC review

app/assets/javascripts/modules/SearchFilter.js, app/assets/stylesheets/components/further_info/_further_info.scss, app/assets/stylesheets/components/search_filter/_search_filter.scss, app/assets/stylesheets/components/search_filter/_settings.scss, app/views/landing_page/_search_filter.html.erb, app/views/landing_page/_search_filter_options.html.erb
@moneyadviceservice/frontend @benlovell 
Changes in line with Alan to accommodate the search filter on small device sizes.
=> 5880 Fix the search filter on small devices

app/assets/javascripts/modules/FurtherInfo.js, app/assets/stylesheets/components/further_info/_further_info.scss
@Guntrisoft @ourmaninamsterdam
=> Fix tooltip so they are only open one at a time

config/locales/cy.yml, config/locales/en.yml
=> Update EN and CY meta tags for the landing page

app/assets/stylesheets/_enhanced.scss, app/assets/stylesheets/components/_locale.scss, app/assets/stylesheets/layouts/_header.scss, app/views/layouts/application.html.erb, config/locales/cy.yml, config/locales/en.yml
@benlovell @benbarnett @lshepstone
=> Add language toggle to the header

app/assets/javascripts/modules/FurtherInfo.js, app/assets/stylesheets/_enhanced.scss, app/assets/stylesheets/_settings.scss, app/assets/stylesheets/components/_banner_list.scss, app/assets/stylesheets/components/advert/_advert.scss, app/assets/stylesheets/components/advert/_settings.scss, app/assets/stylesheets/components/further_info/_further_info.scss, app/assets/stylesheets/components/further_info/_settings.scss, app/assets/stylesheets/components/search_filter/_search_filter.scss, app/assets/stylesheets/layouts/_landing_page.scss, app/views/landing_page/_search_filter_options.html.erb, app/views/landing_page/show.html.erb, config/locales/cy.yml, config/locales/en.yml
=> 5837 landing page changes

config/locales/cy.yml, config/locales/en.yml
=> Welsh error message

app/assets/stylesheets/components/search_filter/_search_filter.scss, app/views/landing_page/show.html.erb, config/locales/cy.yml, config/locales/en.yml
=> Remove desciption text from below the postcode field

elastic_search_mapping.json
Adding fields to reflect recent changes in the `mas-rad_core project`.
=> Adding newly created fields to elasticsearch mapping file

app/assets/images/chevron_left.svg, app/assets/images/chevron_right.svg, app/assets/javascripts/modules/FurtherInfo.js, app/assets/stylesheets/_enhanced.scss, app/assets/stylesheets/_temp_overrides.scss, app/assets/stylesheets/components/education/_all.scss, app/assets/stylesheets/components/education/_education.scss, app/assets/stylesheets/components/pagination/_all.scss, app/assets/stylesheets/components/pagination/_pagination.scss, app/assets/stylesheets/components/pagination/_settings.scss, app/assets/stylesheets/layouts/_results.scss, app/assets/stylesheets/states/_is_open.scss, app/views/kaminari/_next_page.html.erb, app/views/kaminari/_paginator.html.erb, app/views/kaminari/_prev_page.html.erb, app/views/landing_page/show.html.erb, app/views/search/_education_module.html.erb, app/views/search/index.html.erb, config/locales/cy.yml, config/locales/en.yml
=> Add content to the results page and style the pagination

Gemfile.lock, app/forms/search_form.rb, app/serializers/search_form_serializer.rb, elastic_search_mapping.json, spec/features/consumer_filters_by_types_of_advice_spec.rb
I refer you to the individual comments, particularly those in the last commit.
I am about to embark on a magical journey and rework our approach to querying.
=> Filtering on business split/types of advice

app/assets/stylesheets/components/result/_result.scss, app/views/layouts/application.html.erb, app/views/search/_result_list.html.erb, app/views/search/index.html.erb, config/locales/cy.yml, config/locales/en.yml
@moneyadviceservice/frontend @benlovell @lshepstone 
and maybe also @esbel ...if I must.
=> Add Welsh content to the results page

app/views/search/index.html.erb, config/locales/cy.yml, config/locales/en.yml
=> Extract iconography into Ruby loop

Gemfile.lock, app/forms/remote_search_form.rb, app/forms/search_form.rb, app/forms/search_form_filters.rb, app/models/pot_size.rb, app/serializers/search_form_serializer.rb, app/views/landing_page/_search_filter_options.html.erb, app/views/search/index.html.erb, config/locales/cy.yml, config/locales/en.yml, db/schema.rb, elastic_search_mapping.json, spec/features/consumer_filters_by_investment_size_spec.rb, spec/forms/search_form_spec.rb, spec/support/in_person_section.rb
As a result of the separate remote search form being introduced, this story was held up for a bit - we've since split the "online / phone" scenarios for this to another story, so that @amansinghb can move ahead with this piece at least.
This means that the search form filters mixin here is only temporary, and with the next story I'll address merging the forms together (I know how I will approach this already).
Thoughts, @benlovell @esbel?
=> 5838 Pension Pot Size Filter

Gemfile.lock
@benlovell @esbel @tomas-stefano
=> Updates mas-rad_core to 0.0.21

app/views/landing_page/show.html.erb, app/views/search/index.html.erb, spec/features/consumer_search_on_results_list_spec.rb, spec/support/results_page.rb, spec/support/search_criteria_section.rb
* feature definitions and some basic implementation of logic related to search filters form on results page
Part of #5495
=> Change search criteria from search results page

spec/features/consumer_search_on_results_list_spec.rb
Just a feature spec to reflect scenario#2 from TP#5494.
=> Scenario for changing search postcode

app/assets/stylesheets/components/search_filter/_search_filter.scss, app/assets/stylesheets/layouts/_landing_page.scss, app/views/landing_page/show.html.erb, app/views/layouts/application.html.erb
=> Move validation summary into content_for block

app/assets/stylesheets/components/search_filter/_search_filter.scss, app/views/landing_page/_search_filter_options.html.erb, app/views/search/index.html.erb, config/locales/cy.yml, config/locales/en.yml
=> Constrain select box width

app/views/layouts/application.html.erb
@benlovell @esbel @moneyadviceservice/frontend
=> Add canonical tags to the page head

app/views/search/index.html.erb, config/locales/cy.yml, config/locales/en.yml
Thanks to @lshepstone for the Ruby knowledge!
@benlovell @esbel
=> Add no results message to the results page

app/views/layouts/application.html.erb
@esbel @lshepstone @benlovell @benbarnett
=> Add google analytics code to the top of the page

app/views/landing_page/show.html.erb, config/locales/cy.yml, config/locales/en.yml
=> Add RIO link to the landing page

app/forms/search_form.rb, app/views/landing_page/show.html.erb, app/views/layouts/application.html.erb, config/locales/en.yml
@lshepstone @esbel @benlovell 
*Awaiting Welsh translation.*
=> [WIP] Remove method name from the validation message

app/assets/javascripts/modules/SearchFilter.js, app/assets/stylesheets/components/search_filter/_search_filter.scss, app/views/landing_page/show.html.erb
=> Should have been merged into the previous closed branch

config/locales/cy.yml
=> Welsh validation summary

app/views/landing_page/show.html.erb, spec/support/in_person_section.rb, spec/support/remote_section.rb
@benlovell @lshepstone 
...and fix accompanying failing tests.
=> Namespace the landing_page forms to prevent duplicate ids

app/serializers/search_form_serializer.rb
What it says on the tin. Though, this is an attempt, and it's easiest to test this in staging, so ...
@benlovell @amansinghb
=> Ensures the A-Z sort is applied after the types of advice sort.

app/assets/javascripts/application.js, app/assets/javascripts/modules/ResultsFilter.js, app/assets/javascripts/modules/SearchFilter.js, app/assets/javascripts/require_config.js.erb, app/assets/stylesheets/components/result/_result.scss, app/assets/stylesheets/components/search_filter/_search_filter.scss, app/assets/stylesheets/layouts/_results.scss, app/controllers/landing_page_controller.rb, app/controllers/search_controller.rb, app/helpers/application_helper.rb, app/views/landing_page/_search_filter.html.erb, app/views/landing_page/_search_filter_options.html.erb, app/views/landing_page/show.html.erb, app/views/search/index.html.erb, config/initializers/assets.rb, config/locales/cy.yml, config/locales/en.yml, spec/features/face_to_face_filter_for_pension_advice_spec.rb, spec/features/face_to_face_filter_for_various_types_of_advice_spec.rb, spec/features/phone_or_online_filter_for_pension_advice_spec.rb, spec/features/phone_or_online_filter_for_various_types_of_advice_spec.rb, spec/support/in_person_section.rb, spec/support/remote_section.rb
=> 6063 hide and show advice methods (results page)

app/assets/javascripts/application.js, app/assets/javascripts/modules/EducationModule.js, app/assets/javascripts/require_config.js.erb, app/assets/stylesheets/components/education/_education.scss, app/views/search/_education_module.html.erb, config/initializers/assets.rb
=> Add education module toggle

app/assets/stylesheets/components/search_filter/_search_filter.scss, app/assets/stylesheets/layouts/_results.scss, app/controllers/search_controller.rb, app/views/search/index.html.erb, config/locales/cy.yml, config/locales/en.yml
=> 6084 Add validation error messages to the results page

config/locales/cy.yml
Retirement options link in welsh was broken
=> Retirement options link change

app/assets/javascripts/application.js, app/assets/javascripts/modules/ResultsModule.js, app/assets/javascripts/require_config.js.erb, app/assets/stylesheets/components/education/_education.scss, app/assets/stylesheets/components/result/_result.scss, app/assets/stylesheets/components/search_filter/_search_filter.scss, app/assets/stylesheets/layouts/_results.scss, app/views/search/index.html.erb, config/initializers/assets.rb
=> Third attempt at 5781

app/assets/javascripts/modules/ResultsModule.js, app/views/search/index.html.erb
=> Collapsible bugs

app/views/landing_page/_search_filter.html.erb, app/views/search/index.html.erb
Simples.
@benlovell @alexwllms @amansinghb
=> Use the correct translation key for other advice methods.

app/assets/stylesheets/layouts/_results.scss
=> Move back to top link nearer to the top right

app/assets/javascripts/modules/EducationModule.js, app/assets/javascripts/modules/FurtherInfo.js, app/assets/javascripts/modules/ResultsFilter.js, app/assets/javascripts/modules/ResultsModule.js, app/assets/stylesheets/components/education/_education.scss, app/assets/stylesheets/components/result/_result.scss, app/assets/stylesheets/layouts/_results.scss, app/assets/stylesheets/states/_is_hidden.scss, app/views/landing_page/show.html.erb, app/views/search/_education_module.html.erb, app/views/search/index.html.erb
@lshepstone @benlovell @amansinghb
=> Fixes for Firefox, IE8 and flash of hidden content

app/assets/stylesheets/layouts/_results.scss
=> Fix filter in IE8 and add smaller MQ for pagination

app/views/layouts/application.html.erb, config/locales/cy.yml, config/locales/en.yml
=> Add breadcrumbs link back in

app/assets/javascripts/modules/SearchFilter.js, app/views/landing_page/_search_filter.html.erb
=> Add CSS class to prevent flash of hidden content

app/views/glossary/show.html.erb, app/views/landing_page/show.html.erb, app/views/layouts/application.html.erb, app/views/search/index.html.erb, config/application.rb, config/locales/cy.yml, config/locales/en.yml
@benlovell @amansinghb @lshepstone 
Specifically look at the locale toggle in application.html please.
=> Localisation fixes

app/assets/stylesheets/layouts/_landing_page.scss, app/assets/stylesheets/layouts/_results.scss, app/views/landing_page/show.html.erb
=> Add a gradient to the header and move the back to top link

app/assets/stylesheets/_settings.scss, app/assets/stylesheets/layouts/_results.scss, app/forms/search_form.rb, app/views/search/index.html.erb, config/locales/cy.yml, config/locales/en.yml, spec/forms/search_form_spec.rb
@lshepstone @amansinghb @benlovell
=> Add explanatory message on the results page

app/assets/stylesheets/components/search_filter/_search_filter.scss, app/assets/stylesheets/layouts/_results.scss, app/views/landing_page/_search_filter_options.html.erb
=> 6159 Advice types line wrapping

app/views/landing_page/_search_filter_options.html.erb, app/views/landing_page/show.html.erb, config/locales/cy.yml, config/locales/en.yml
@benlovell @amansinghb @lshepstone 
Still awaiting Welsh but lets get it in anyway.
=> Content changes

app/views/layouts/application.html.erb
Entering JS snippet to allow CrazyEgg to track where users click on the
RAD pages and where they scroll.
Tested Locally, all is well
=> JS Snippet for CrazyEgg tracking

app/assets/stylesheets/layouts/_results.scss, app/views/search/index.html.erb, config/locales/cy.yml, config/locales/en.yml
@benlovell @lshepstone 
I had a go at fixing story 6183 changing the remote results message. Sure there's a better way to refactor it though.
=> Add conditional for remote results message

app/assets/stylesheets/components/_education.scss, app/assets/stylesheets/layouts/_results.scss, config/locales/en.yml
=> Education module content

config/locales/cy.yml, config/locales/en.yml
=> Change content for adviser distance label

config/locales/cy.yml
=> Reorder pension wise link and description

Gemfile.lock
Use the latest version of `mas-rad_core` for support to index firms when they're updated.
=> 6046 Index Firm when it's updated

app/assets/stylesheets/components/_brand_logo.scss, app/assets/stylesheets/components/_result.scss, config/locales/en.yml
=> Post live review

Gemfile.lock, app/views/search/index.html.erb, elastic_search_mapping.json, spec/support/firm_section.rb
=> 6222 Shows line two of the address in search results

app/views/search/index.html.erb
=> Only show line two of the address if it's present.

app/assets/stylesheets/layouts/_results.scss, app/views/search/index.html.erb, config/locales/cy.yml, config/locales/en.yml
@benlovell @amansinghb @Guntrisoft
=> Remove ordered by explanatory message

Gemfile.lock, app/views/search/index.html.erb, config/locales/cy.yml, config/locales/en.yml
Also adds translated text for distances.
=> Bumps core to humanize distances

config/locales/cy.yml
@benlovell @amansinghb @Guntrisoft
=> Update content in CY education module

app/assets/stylesheets/components/_search_filter.scss, app/views/landing_page/_search_filter.html.erb, app/views/landing_page/_search_filter_options.html.erb, app/views/landing_page/show.html.erb
=> Move the search button on the landing page

app/views/landing_page/show.html.erb, config/locales/cy.yml, config/locales/en.yml
=> Various content changes

app/assets/stylesheets/components/_address.scss, app/assets/stylesheets/components/_keyword.scss, app/views/search/index.html.erb, config/locales/cy.yml, config/locales/en.yml
=> Collapsible address block

app/assets/stylesheets/components/_result.scss, app/views/search/index.html.erb
=> Separate lists of advice methods

app/assets/stylesheets/layouts/_results.scss, app/views/search/index.html.erb, config/locales/cy.yml, config/locales/en.yml
=> Add feedback link to the results page

app/assets/stylesheets/components/_address.scss, app/assets/stylesheets/components/_result.scss, app/assets/stylesheets/layouts/_results.scss, app/views/search/index.html.erb
@benlovell @amansinghb @Guntrisoft
=> Minor style changes

app/assets/stylesheets/_settings.scss, app/assets/stylesheets/components/_back_to_top.scss, app/assets/stylesheets/layouts/_results.scss, app/views/search/index.html.erb, config/locales/en.yml
@benlovell @Guntrisoft @amansinghb
=> Fix feedback link href and general layout

Gemfile, Gemfile.lock
=> Add auto-prefixer-rails to the Gemfile

README.md
=> Add install and usage instructions to README.md

README.md
=> Update readme after fresh test of the install steps

app/helpers/application_helper.rb, app/views/search/index.html.erb
=> Remove link style; glossary now open in the same page

app/assets/stylesheets/components/_result.scss, app/assets/stylesheets/layouts/_landing_page.scss, app/views/landing_page/show.html.erb, app/views/search/index.html.erb
=> Style changes to comply with RAD

app/assets/javascripts/modules/ResultsModule.js, app/assets/stylesheets/components/_education.scss, app/assets/stylesheets/components/_result.scss, app/views/search/index.html.erb
=> Heading fix

app/assets/stylesheets/components/_accreditation.scss, app/assets/stylesheets/components/_address.scss, app/assets/stylesheets/layouts/_results.scss, app/views/landing_page/show.html.erb, app/views/search/partials/firm/_contact_details.html.erb, app/views/shared/_svg_icons.html.erb, config/locales/cy.yml, config/locales/en.yml, spec/features/consumer_views_a_search_result_spec.rb
Also needs Welsh.
[Edit: Doesn't need Welsh anymore]
=> Dac fixes 3

app/assets/stylesheets/layouts/_responsive.scss
Initial is not supported in IE.
=> Change `l-desktop-only` to use display block over display initial.

Gemfile, Gemfile.lock, db/schema.rb, spec/features/channel_filter_on_results_page_spec.rb, spec/features/consumer_views_a_search_result_spec.rb
See 	Move `website_address` attribute from principal to firm.
=> Move `website_address` attribute from principal to firm.

config/locales/cy.yml, config/locales/en.yml
https://github.com/moneyadviceservice/rad/pull/269 introduces 2 new qualifications. We need to introduce mappings here so this application knows how to display (or not in this case) this data.
=> Update the qualification to accreditation mappings to add 2 new mappings

Rakefile, package.json
Small housekeeping task to ensure that all projects are using a consistent approach to running the js tests.
=> Making JavaScript test running consistent across projects.

app/assets/stylesheets/_enhanced.scss, app/assets/stylesheets/components/_firm.scss, app/assets/stylesheets/components/_outline_button.scss, app/assets/stylesheets/layouts/_firm.scss, app/controllers/firms_controller.rb, app/forms/search_form.rb, app/helpers/application_helper.rb, app/serializers/search_form_serializer.rb, app/views/firms/partials/_content.html.erb, app/views/firms/partials/_header.html.erb, app/views/firms/show.html.erb, app/views/search/partials/_firm.html.erb, app/views/shared/_svg_icons.html.erb, config/locales/en.yml, config/routes.rb, spec/controllers/firms_controller_spec.rb, spec/forms/search_form_spec.rb, spec/serializers/search_form_serializer_spec.rb
=> Add heading for firm profile page

.env.example, .gitignore, Gemfile, Gemfile.lock, README.md, app/assets/javascripts/application.js, app/assets/javascripts/modules/FirmMap.js, app/assets/javascripts/modules/NestedOptions.js, app/assets/javascripts/require_config.js.erb, app/assets/stylesheets/components/_firm.scss, app/controllers/firms_controller.rb, app/helpers/application_helper.rb, app/views/firms/partials/_content.html.erb, app/views/firms/partials/_firm_details.html.erb, bower.json.erb, config/initializers/assets.rb, config/locales/en.yml, spec/controllers/firms_controller_spec.rb, spec/fixtures/vcr_cassettes/geocode_search_form_postcode.yml, spec/javascripts/fixtures/FirmMap.html, spec/javascripts/test-main.js, spec/javascripts/tests/FirmMap_spec.js, spec/javascripts/tests/NestedOptions_spec.js
=> Add map to profile

app/assets/stylesheets/_temp_overrides.scss, app/assets/stylesheets/components/_further_info.scss, app/assets/stylesheets/components/_pagination.scss, app/assets/stylesheets/components/_search_filter.scss, app/views/kaminari/_next_page.html.erb, app/views/kaminari/_prev_page.html.erb, app/views/search/index.html.erb, app/views/search/partials/_footer_links.html.erb, app/views/search/partials/_results.html.erb
Raised purely to merge https://github.com/moneyadviceservice/rad_consumer/pull/208 into master. See that PR for review and approval.
=> [DEV APPROVED] IE 11 fixen (merge to master)

app/assets/stylesheets/components/_advert.scss, app/assets/stylesheets/layouts/_landing_page.scss, app/views/landing_page/show.html.erb, config/locales/cy.yml
Raised purely to merge https://github.com/moneyadviceservice/rad_consumer/pull/209 into master. See #209 for review/approval.
=> [WIP] Welsh translations (merge PR)

config/locales/cy.yml
Adds in the missing translations from #212
=> [DEV APPROVED] add missing Welsh translations for search filters

config/locales/cy.yml, config/locales/en.yml, spec/features/results_filter_on_quals_and_accreds_spec.rb, spec/forms/search_form_spec.rb
We needed to reduce the number of options in the qualifications and accreditations filter.
Plus Welsh arrived so it's been added here.
=> [DEV APPROVED] Prune filters and add welsh

app/assets/stylesheets/_enhanced.scss, app/assets/stylesheets/_settings.scss, app/assets/stylesheets/components/_callout.scss, app/assets/stylesheets/components/_firm.scss, app/assets/stylesheets/layouts/_firm.scss, app/views/firms/partials/_firm_details.html.erb, config/locales/cy.yml, config/locales/en.yml
Adds callout section to profile page (green box)
=> [DEV APPROVED] callout area

app/views/firms/partials/_firm_details.html.erb, config/locales/cy.yml, config/locales/en.yml
=> [DEV APPROVED] Add "Transferring a pension" advice type in the profile

Gemfile, Gemfile.lock, app/helpers/firm_helper.rb, app/views/firms/partials/_callout_item.html.erb, app/views/firms/partials/_firm_details.html.erb, spec/helpers/firm_helper_spec.rb
* Bumping mas-rad_core, which adds the default value of firm.minimum_fixed_fee.
* Removing check on presence of minimum fixed fee as it is never nil anymore.
* Bit of refactoring of the view callout items.
=> Default minimum fixed fee to zero

app/assets/stylesheets/components/_firm.scss, app/assets/stylesheets/layouts/_firm.scss, app/views/firms/partials/_content.html.erb
Minor padding and margin changes to ensure the heading, tabs, and content are aligned.
=> [DEV APPROVED] align headers, tabs, and content

config/locales/cy.yml, config/locales/en.yml
- updates explanatory text on the company profile page
=> [DEV APPROVED] id: 6905, comment: copy change (en and cy)

app/helpers/firm_helper.rb, app/views/firms/partials/_firm_details.html.erb, config/locales/cy.yml, config/locales/en.yml, spec/helpers/firm_helper_spec.rb
=> Rework the languages display as 'Additional languages'

config/locales/cy.yml, config/locales/en.yml
This PR updates the RAD footer with the new phone number and correct webchat opening hours.
Call centre:
Webchat:
Call centre:
Webchat:
=> [DEV APPROVED] Updating phone number and opening hours

config/locales/cy.yml, config/locales/en.yml
PDFs have been copied across to the Azure CDN. Updates the URLs to use new CDN.
=> update PDF asset urls to point to Azure CDN

app/views/firms/partials/_recently_visited.html.erb, config/locales/cy.yml, config/locales/en.yml
=> Adding message to show which firms are remote in the recently visited firms list.

app/views/layouts/application.html.erb, spec/javascripts/fixtures/NestedOptions.html, spec/javascripts/tests/NestedOptions_spec.js
This adds the tag to RAD that is needed to run A/B Tests. After consulting with RedEye we decided to add a single tag to the codebase: the targeted environment is controlled from the Optimizely Control Panel.
=> [DEV APPROVED] TP: 7441, Comment: Adds Optimizely tag to RAD

app/assets/javascripts/modules/ResultsFilter.js, app/serializers/search_form_serializer.rb, app/views/search/partials/filters/_advice_method.html.erb, spec/features/consumer_search_on_results_list_spec.rb, spec/features/landing_face_to_face_search_spec.rb, spec/features/results_face_to_face_search_spec.rb, spec/features/search_by_firm_name_spec.rb, spec/serializers/search_form_query_serializer_spec.rb
Hey @Tr4pSt3R here's how I suggest we refactor the JS for the Search Filter on RAD Consumer. This means if we end up adding more search options we won't need to add any more JavaScript, or keep incrementing the HTML attributes.
I'm pretty sure all of the functionality is preserved (and the Karma tests pass), but please could you check it manually as well?
=> [MERGED] 7497 - Simplifying JavaScript on search filter

Gemfile, Gemfile.lock, app/assets/javascripts/modules/ResultsFilter.js, app/assets/javascripts/require_config.js.erb, app/assets/stylesheets/_enhanced.scss, app/assets/stylesheets/components/_search_filter.scss, app/assets/stylesheets/components/_validation.scss, app/assets/stylesheets/layouts/_landing_page.scss, app/forms/filters/advice_method.rb, app/views/landing_page/_search_filter.html.erb, app/views/search/partials/filters/_advice_method.html.erb, config/locales/cy.yml, config/locales/en.yml, elastic_search_mapping.json, spec/features/channel_filter_on_results_page_spec.rb, spec/features/consumer_search_on_results_list_spec.rb, spec/features/consumer_views_a_search_result_spec.rb, spec/features/firm_profile_advisers_tab_spec.rb, spec/features/firm_profile_for_in_person_search_spec.rb, spec/features/landing_face_to_face_search_spec.rb, spec/features/results_filter_on_quals_and_accreds_spec.rb, spec/features/search_by_firm_name_spec.rb, spec/support/feature_spec_helper.rb, spec/support/in_person_section.rb
There are currently three options in 'Find a Retirement advisor' ,first option is selected by default.  A single line divided first two options and third option and third option has 'alternatively'.
The changes are to remove the line and alternatively text and no options should be selected on load. 
Please note: The changes in this PR rely on an updated version of Dough which has a modified validation link (Which does not include a link to the error'd field) Dough PR: https://github.com/moneyadviceservice/dough/pull/280
| Current | New |
|--------|------|
|<img src="https://cloud.githubusercontent.com/assets/13165846/20706153/c06a445c-b61d-11e6-99d8-bb214418b9f8.png" width="300" />|<img src="https://cloud.githubusercontent.com/assets/13165846/20706178/dd250726-b61d-11e6-802f-a3aca3423828.p …
=> [DEV APPROVED] 7756 - Find a retirement adviser options new design

Gemfile, Gemfile.lock
More details here: https://github.com/moneyadviceservice/mas-rad_core/pull/157
=> [DEV APPROVED] - Update mas-rad_core gem

.ruby-gemset
Add ruby-gemset file so Jenkins can use pre-bundled gems
=> Add .ruby-gemset

README.md, config/locales/cy.yml, config/locales/en.yml, features/cassettes/algolia/search-filters/filter-by-accreditations-and-qualifications/post/1/indexes/firm-advisers-test/query.yml, features/cassettes/algolia/search-filters/filter-by-pension-pot-or-investment-size/post/1/indexes/firm-advisers-test/query.yml, features/cassettes/algolia/search-filters/filter-by-type-of-advice/post/1/indexes/firm-advisers-test/query.yml, features/search_filters.feature, spec/forms/search_form_spec.rb
[TP 10564](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiRkRBMzk3RTBGNjU3NDg1RDM4QzczMTJFNzI5MDFBN0MifQ==&boardPopup=userstory/10564/silent)
[TP 10544](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiRkRBMzk3RTBGNjU3NDg1RDM4QzczMTJFNzI5MDFBN0MifQ==&boardPopup=userstory/10544/silent) added 2 new qualifications that an adviser might hold. This pr provides the functionality for users to filter advisers by these new qualifications.
=> [DEV APPROVED] TP 10564 Additional qualifications for searching firms

Gemfile
Needed to fix issues in PR-372
=> Adds Listen Gem

Gemfile
Reverts moneyadviceservice/rad_consumer#373
=> Revert "Adds Listen Gem"

app/assets/stylesheets/layouts/_office.scss
Reverts moneyadviceservice/rad_consumer#375
=> Revert "Restores deleted styles"

Gemfile, Gemfile.lock, spec/spec_helper.rb
This PR moves rad consumer to depend on master rather than a branch
=> Tp 11190/migrate from branch to master

app/views/layouts/application.html.erb
[TP-12190](https://maps.tpondemand.com/entity/12190-clone-rad-with-no-headerfooter-for)
Remove Partials
=> TP-12190 Remove Header and Footer Partials

app/views/layouts/application.html.erb
[TP-12190](https://maps.tpondemand.com/entity/12190-clone-rad-with-no-headerfooter-for)
Remove Partials
=> TP 12190 Remove Contacts

app/views/landing_page/show.html.erb, config/locales/cy.yml, config/locales/en.yml
[TP12196](https://maps.tpondemand.com/entity/12196-rad-homepage-update-videos)
This PR updates both homepage video's URLs and transcripts. A couple of new translation keys were implemented to support this.
=> 12196 - Updates Videos URL and Transcripts

app/views/firms/partials/_guide_link.html.erb, app/views/landing_page/show.html.erb, app/views/search/partials/_search_filter.html.erb, config/locales/cy.yml, config/locales/en.yml
[TP-12568](https://maps.tpondemand.com/entity/12568-rad-links-need-to-be-updated)
This work updates a number of links on RAD and also ensures that they are all set to open in a new window.
=> 12568 links update new window

app/helpers/application_helper.rb
[TP12543](https://maps.tpondemand.com/restui/board.aspx?#page=userstory/12543)
This PR swap RAD register link on rad consumer
=> swap RAD register link

app/views/layouts/application.html.erb
Ensures pages scroll to the top when reloading inside of an iframe.
=> Add scroll to top message

app/views/contact_methods/_call_us.html.erb, app/views/firms/partials/_firm_links.html.erb, app/views/firms/partials/_offices.html.erb
These aren't working in various browsers.
=> Try _blank targets for phone/email links

app/views/layouts/application.html.erb
These have moved so need to be updated accordingly.
=> Rewrite legacy asset paths
