moneyadviceservice/rad_consumer

app/assets/javascripts/application.js
app/assets/javascripts/modules/FurtherInfo.js
app/assets/javascripts/require_config.js.erb
app/assets/stylesheets/_enhanced.scss
app/assets/stylesheets/base/_headings.scss
app/assets/stylesheets/components/_further_info.scss
app/assets/stylesheets/components/_tooltip.scss
app/assets/stylesheets/components/further_info/_all.scss
app/assets/stylesheets/components/further_info/_further_info.scss
app/assets/stylesheets/components/further_info/_settings.scss
app/assets/stylesheets/layouts/_landing_page.scss
app/views/landing_page/show.html.erb
app/views/layouts/application.html.erb
config/initializers/assets.rb
config/locales/en.yml

@benbarnett @benlovell 
Added RequireJS.
Added a FurtherInfo module which displays large quantities of explanatory information on click. Similar to a expand/collapse function in an FAQ section.
Added temporary styles for the `union-statement` which has not been through proper design yet.
Needs JS tests and possible promotion to Dough (if useful).

Add a FurtherInfo (quasi-tooltip) JS module

---

app/views/landing_page/show.html.erb
config/locales/en.yml

@moneyadviceservice/frontend @benlovell 
As the retirement income option tool is currently not available I have added in a short disclaimer (to be authorised by props I'm sure) and disabled the call to action.

Disable the retirement income options link

---

app/assets/stylesheets/layouts/_landing_page.scss
app/views/landing_page/_search_filter.html.erb
app/views/layouts/application.html.erb

Have moved the error validation summary temporarily to the top of the page. I have emailed Gavin at DAC to check on whether it is accessible. It may need to be moved further down the page. We'll have to see.
@moneyadviceservice/frontend @benlovell

Move the error validation up to the top of the page

---

app/forms/search_form.rb
lib/geocode.rb
spec/forms/search_form_spec.rb
spec/lib/geocode_spec.rb

Prior to this PR, the user would have to provide postcodes in uppercase, to
pass the validation checks. This didn't make much sense as we were then
uppercasing the postcode as part of the normalisation occurring in
`Geocode.call`.

Shuffles around responsibilities for normalising

---

spec/features/consumer_searches_by_postcode_only_spec.rb
spec/spec_helper.rb
spec/support/elastic_search_helper.rb

I would like to re-use methods `with_fresh_index` and `with_elastic_search` methods in features for upcoming remote advisories search functionality. This PR attempts to extract them into a RSpec mixin. Lemme know what you think.
@lshepstone @benlovell

Extract ElasticSearchHelper from consumer search by postcode

---

app/assets/stylesheets/components/search_filter/_search_filter.scss
app/views/landing_page/show.html.erb

@lshepstone @moneyadviceservice/frontend
Override to the Dough class `.form` which is applying a top margin.

Fix the margin-top issue on the search filter

---

Gemfile.lock
spec/support/elastic_search_helper.rb

Required a slight change to trigger indexing of factory data. Also took
the opportunity to break out the individual elasticsearch helper
actions since `with_fresh_index!` was becoming unwieldy.

Includes fanout of geocode/index jobs from core

---

spec/features/consumer_searches_by_postcode_only_spec.rb

When working on #5725, I realised that `contain_exactly` method checks for set equality (i.e. does two collections have the same items), rather than list equality (the same items in the same order). Before proposed change, one could change order of the companies in the example and it wouldn't fail the test.

Distance search firms order spec - actually perform order check

---

Gemfile.lock

Page counts were being miscalculated in some instances.

Bumps core to resolve issue with pagination

---

app/serializers/remote_search_form_serializer.rb
spec/features/consumer_filters_by_types_of_advice_spec.rb
spec/features/consumer_searches_by_postcode_only_spec.rb
spec/features/consumer_searches_remote_advice_spec.rb
spec/support/remote_results_page.rb
spec/support/results_page.rb

Scenario: Selecting phone advice
Given that I am on the RAD landing page
When I submit a search selecting phone advice 
Then I am shown FIRMS and SUBSIDIARIES that provide advice by phone 
And they are ordered alphabetically, (A-Z)
Scenario: Selecting phone AND online advice
Given that I am on the RAD landing page
When I submit a search selecting online AND phone advice
Then I am shown FIRMS and SUBSIDIARIES that provide advice by phone OR online
And I am shown FIRMS and SUBSIDIARIES that provide advice by phone AND online
And they are ordered alphabetically, (A-Z)

#5725 Remote search scenarios 1&3

---

app/controllers/remote_search_controller.rb
app/controllers/search_controller.rb
app/forms/remote_search_form.rb
app/views/landing_page/show.html.erb
config/locales/cy.yml
config/locales/en.yml
spec/features/consumer_searches_remote_advice_spec.rb
spec/support/remote_section.rb

TL;DR: validate that user checked phone or online;
```
Scenario: Consumer tries to run a phone / online advice search WITHOUT selecting phone or online options
Given that I am on the RAD landing page
When I submit a search via the phone / online workflow
And I have NOT selected phone or online (even if I have selected a type of advice e.g. Equity release, Wills and probate etc.)
Then I am shown an error message: To continue please select online, telephone or both and run your search again’
And I CANNOT run my search until I select online and / or telephone 
```

#5725 scenario #5 - form validation

---

app/forms/remote_search_form.rb
app/serializers/remote_search_form_serializer.rb
spec/features/consumer_searches_remote_advice_spec.rb
spec/support/remote_section.rb

Scenario #4 of #5725:
```
Scenario: Selecting phone and/or online advice with advice filters
Given that I am on the RAD landing page
When I submit a search selecting online and/or phone advice with selected 'types of advice' filters
Then I am show FIRMS AND SUBSIDIARIES that provide advice by phone and/or online (based on the rules above for selecting phone advice, online advice or phone and online advice)
And provide the 'type of advice' I have selected 
And are ordered in alphabetical order (A-Z)
```
Implementation is partially based on existing implementation of filters for `SearchForm`.

#5725 Support for filtering by advice type

---

app/controllers/remote_search_controller.rb
config/locales/cy.yml
config/locales/en.yml
config/routes.rb

Fix meta/title tags by providing references in the`YAML` translations.
Also, refactored `RemoteSearchController#index` action to #show to improve consistency with `SearchController` class
@alexwllms

#6019 Fix meta/title tags on remote search page

---

elastic_search_mapping.json

Solution for the problem Kemi mentioned on slack earlier today (https://slack-files.com/files-tmb/T024GQVEQ-F04142H4C-47dfe46c16/screen_shot_2015-03-13_at_13.17.17_1024.png).
ES Sorting expression was using case sensitive index to sort records. This PR addresses that issue. 
It will require developers to build all indices from scratch.

Case insensitive company name sort

---

Gemfile.lock
app/forms/search_form_filters.rb
elastic_search_mapping.json
spec/features/consumer_filters_by_investment_size_spec.rb
spec/features/consumer_filters_by_types_of_advice_spec.rb

Selecting pension transfer options was not including this particular
filter among the other percentage filters.
I've marked one spec step pending as we'll need to clarify how the two
options interact. I'm not sure much consideration was made for that
area.

Reworks pension filtering and sorting

---

app/serializers/remote_search_form_serializer.rb
spec/features/consumer_searches_remote_advice_spec.rb

Currently, if you select a remote advice method (e.g. phone) and an advice method filter (e.g. wills), you get on search results companies that:
* provide phone advice on wills and probate (that's ok)
* phone advice, but no wills/probate advice (that's wrong)
* in person advice only (i.e. postcode search) on wills/probate (that's wrong)
This pull request is to address this issue. I'm not sure if it's already been logged to TP, so no issue#.

Fix remote advice + advice filters query matching bug

---

Gemfile
Gemfile.lock
app/forms/search_form.rb
app/serializers/search_form_serializer.rb
app/views/landing_page/_search_filter_options.html.erb
elastic_search_mapping.json
spec/features/consumer_filters_by_investment_size_spec.rb
spec/features/consumer_filters_by_types_of_advice_spec.rb
spec/forms/search_form_spec.rb
spec/support/in_person_section.rb

These fields were not part of the business split ranking and filtering. Now
they are calculated as other percentage fields.

Includes retirement products and pension transfer

---

spec/features/face_to_face_filter_for_pension_advice_spec.rb
spec/features/phone_or_online_filter_for_pension_advice_spec.rb
spec/support/remote_section.rb

Massages the language around the pension advice feature specs to make way for scenarios using the phone or online advice method.
@benlovell @esbel @amansinghb

Pension advice feature specs

---

app/forms/search_form.rb
app/views/search/index.html.erb
spec/features/channel_filter_on_results_page_spec.rb
spec/features/consumer_search_on_results_list_spec.rb
spec/support/landing_page.rb
spec/support/search_criteria_section.rb

Note: redirects after submitting invalid search criteria (e.g. no postcode for face2face, neither phone/online for remote advice) will come as a separate story, as validation messages are still pending design and there'll be minor tweaks in functionality
thus: lines 50/51&61/62 are temporary

Switching advice type from RAD search results page #5496

---

app/views/search/index.html.erb

Alex has hidden advice type fields, so it rendered testing the form impossible. This is a temporary solution to allow a more thorough testing until it's fixed.

Unhide advice type fields on search results form

---

app/helpers/application_helper.rb
app/views/search/index.html.erb
config/locales/en.yml

When they're listed as `ignored` in the translations lookup they'll not
be outputted in the search results.

Makes missing logos explicit

---

Gemfile.lock
app/serializers/search_form_serializer.rb
elastic_search_mapping.json
spec/features/consumer_searches_by_postcode_only_spec.rb

Now filters based on proper adviser radius. Also orders by geographic
distance. The distance filter is essentially a fudge to provide range
ordering as shapes do not support this behaviour. It works, and seems
to be reasonably performant. We could certainly trade some accuracy for
speed, if necessary.

Adds adviser range filtering

---

Gemfile.lock
app/forms/search_form.rb
lib/geocode.rb
spec/features/consumer_searches_by_postcode_only_spec.rb
spec/fixtures/vcr_cassettes/postcode_cannot_be_geocoded.yml
spec/fixtures/vcr_cassettes/rg2_1aa.yml
spec/forms/search_form_spec.rb
spec/lib/geocode_spec.rb

Allows the space in postcodes to be optional, and does not remove any spaces before the postcode is geocoded. This intentionally does not change the existing validation.
@benlovell

6175 Postcode spaces

---

app/views/search/index.html.erb
spec/features/landing_face_to_face_filter_for_other_advice_types_spec.rb
spec/features/landing_face_to_face_filter_for_pension_advice_spec.rb
spec/features/landing_face_to_face_search_spec.rb
spec/features/landing_phone_or_online_filter_for_other_advice_types_spec.rb
spec/features/landing_phone_or_online_filter_for_pension_advice_spec.rb
spec/features/landing_phone_or_online_search_spec.rb
spec/features/results_face_to_face_filter_for_other_advice_types_spec.rb
spec/features/results_face_to_face_filter_for_pension_advice_spec.rb
spec/features/results_face_to_face_search_spec.rb
spec/features/results_phone_or_online_filter_for_other_advice_types_spec.rb
spec/features/results_phone_or_online_filter_for_pension_advice_spec.rb
spec/features/results_phone_or_online_search_spec.rb
spec/fixtures/vcr_cassettes/postcode_cannot_be_geocoded.yml
spec/support/elastic_search_helper.rb
spec/support/landing_page.rb
spec/support/results_page.rb
spec/support/search_form_section.rb

This adds a number of specs that cover search scenarios for both face to face and phone and online channels, including error scenarios. For the specs in question, they now read as follows
Landing page, consumer requires general advice over the phone or online
Using only the phone advice method
Using only the online advice method
Using no advice method
Using both the phone and online advice methods
Results page, consumer requires various types of advice over the phone or online
Filter for various types of advice
Results page, consumer requires advice on various topics in person
Filter for various types of advice
Results page, consumer requires general advice over the phone or online
Using only the phone advice method
Using only the online advice method
Using no advice method
Using both the …

Additional feature specs for better coverage

---

config/locales/cy.yml

On the welsh site the links to guides were english, changed to welsh.
Tested locally, links work successfully

Links to guides in welsh

---

app/serializers/search_form_serializer.rb
spec/features/landing_face_to_face_filter_for_other_advice_types_spec.rb
spec/features/landing_phone_or_online_filter_for_other_advice_types_spec.rb
spec/features/results_face_to_face_filter_for_other_advice_types_spec.rb
spec/features/results_phone_or_online_filter_for_other_advice_types_spec.rb

We still query by types of advice, but this removes the ordering
element. Thankfully, this also removes the need for dynamic scripting
and simplifies our approach greatly.

Removes types of advice rankings

---

config/locales/en.yml

As a result of changing the types of advice ranking for search results
the ‘how were these results decided’ text needed to be changed

Change to results decided text

---

app/assets/stylesheets/_enhanced.scss
app/assets/stylesheets/_print.scss
app/views/search/index.html.erb

@benbarnett @benlovell @Guntrisoft 
Simple vertical layout of the print stylesheet.

Add initial print styles template

---

Gemfile.lock
app/serializers/search_form_serializer.rb
spec/features/landing_face_to_face_search_spec.rb

* Bumps core for distance retrieval changes
* Ensures we always order by `registered_name` at least

Order by geo distance and/or registered name

---

app/views/search/index.html.erb
spec/features/consumer_views_a_search_result_spec.rb

Depending on the seed, this spec was failing due to an ordering issue.
If many `InvestmentSize` options had been created in prior specs, the
numbering wasn't starting from `1` thus throwing out the logic around
determining whether the firm has a minimum pot size.

Resolves ordering issues with spec

---

app/assets/javascripts/modules/ResultsModule.js
app/assets/stylesheets/components/_further_info.scss
app/helpers/application_helper.rb
app/views/landing_page/_search_filter.html.erb
app/views/landing_page/_search_filter_options.html.erb
app/views/search/index.html.erb
config/locales/cy.yml
config/locales/en.yml

There's a huge raft of DAC fixes in this project so I'm going to PR them in chunks.
https://github.com/moneyadviceservice/rad_consumer/commit/78edb8c90839b4b329901d7b2c6b87a83c182529 — DAC wanted this marked up as required. I considered using the dough frontend validator but I thought it'd be easier to use the browser validation and let older browsers fall back to seeing the existing server-side validation messages.
https://github.com/moneyadviceservice/rad_consumer/commit/8435dfb272d7c73f13088d2ac0dffaea4e5f751d — For a few reasons the expandable sections needed to be applied and remove on resize events, for instance because increasing the text size in the browser actually changes the resolution of the window. I:
* Added an event to trigger a function with the applying code in.
* Added …

DAC fixes 1

---

app/helpers/search_helper.rb
app/views/search/index.html.erb
config/locales/cy.yml
config/locales/en.yml
spec/features/channel_filter_on_results_page_spec.rb
spec/support/results_page.rb

Adds a little bit of copy to the top of the search results page that tells you how they're ordered — depending on what kind of search you've done.

Add notice on sort order for search results.

---

.travis.yml
package.json
spec/javascripts/tests/NestedOptions_spec.js

We discovered yesterday that a JS spec was failing in this codebase. It appears to have never actually worked, but Travis CI hasn't been running the JS test suite and no new JS functionality has been added in the last few months so it has gone unnoticed.
The functionality is around showing / hiding content when checkboxes are selected (you can see it working on https://directory.moneyadviceservice.org.uk/en). This PR does 3 things:
* Fixes the setup of existing tests, and adds some more just to emphasise the current behaviour
* Updates `package.json` so we can simply invoke `npm test` to run the js tests.
* Updates `.travis.yml` to ensure we're always running the JS test suite.

Fix tests. Ensure travis runs js specs.

---

app/serializers/search_form_serializer.rb
spec/features/consumer_searches_remote_advice_spec.rb
spec/features/landing_face_to_face_filter_for_other_advice_types_spec.rb
spec/features/landing_phone_or_online_filter_for_other_advice_types_spec.rb
spec/features/landing_phone_or_online_filter_for_pension_advice_spec.rb
spec/features/landing_phone_or_online_search_spec.rb
spec/features/results_phone_or_online_filter_for_other_advice_types_spec.rb
spec/features/results_phone_or_online_filter_for_pension_advice_spec.rb
spec/features/results_phone_or_online_search_spec.rb

This change accompanies the back-end data collection change in https://github.com/moneyadviceservice/rad/pull/275.
The rules for whether a firm should appear in location/postcode or remote-advice-only based searches are now as follows:
Should only be firms who have ticked:
* 1..* face-to-face advice types and 
* 0..* remote advice types (i.e. ticking any of these is **optional** if a face-to-face option is checked)
Should only be firms who have ticked:
* 0 face-to-face advice types and
* 1..* remote advice types
There are currently only about 11 firms who are really remote only. The remote search currently returns these plus any face-to-face firms who also offer some remote options (which is circa 2000 results).
So we changed the ElasticSearch query for the remote-advice search to …

Update remote search to ONLY return firms that offer phone or online advice and NOT face-to-face advice

---

.rubocop.yml
.travis.yml
Gemfile
Gemfile.lock
Rakefile
app/forms/search_form.rb
app/serializers/search_form_serializer.rb
spec/features/channel_filter_on_results_page_spec.rb
spec/features/consumer_search_on_results_list_spec.rb
spec/features/consumer_views_a_search_result_spec.rb
spec/features/landing_face_to_face_filter_for_other_advice_types_spec.rb
spec/features/landing_face_to_face_search_spec.rb
spec/features/results_face_to_face_filter_for_other_advice_types_spec.rb
spec/forms/search_form_spec.rb
spec/helpers/search_helper_spec.rb
spec/lib/geocode_spec.rb
spec/support/elastic_search_helper.rb

Adds Rubocop.
Rules seeded form the rad project.
Bulky fixture creation methods under `spec/features` are excluded from Metrics/LineLength and Metrics/MethodLength checks. But all other checks run as per rad.

Add Rubocop and fix things

---

README.md

Tiny PR to add a note to the readme about running a rake task to populate the elastic search index, otherwise you won't see any search results.

add a note about rake task needed to be run

---

Gemfile
Gemfile.lock
db/schema.rb
spec/features/consumer_search_on_results_list_spec.rb
spec/features/consumer_searches_remote_advice_spec.rb
spec/features/consumer_views_a_search_result_spec.rb
spec/features/landing_face_to_face_filter_for_other_advice_types_spec.rb
spec/features/landing_face_to_face_filter_for_pension_advice_spec.rb
spec/features/landing_face_to_face_search_spec.rb
spec/features/landing_phone_or_online_filter_for_other_advice_types_spec.rb
spec/features/landing_phone_or_online_filter_for_pension_advice_spec.rb
spec/features/results_face_to_face_filter_for_other_advice_types_spec.rb
spec/features/results_face_to_face_filter_for_pension_advice_spec.rb
spec/features/results_face_to_face_search_spec.rb
spec/features/results_phone_or_online_filter_for_other_advice_types_spec.rb
spec/features/results_phone_or_online_filter_for_pension_advice_spec.rb

* Bumps mas-rad_core to 0.0.73
* Migrate the schema to reflect rad_core changes
* Updates a number of specs to reflect modelling changes in firms
* Added comments above factory generated firms that appear to be superfluous, but may be intentionally there to highlight counting errors when things don't work correctly.

Update mas-rad_core to 0.0.73 and fix tests to reflect new changes

---

spec/features/landing_face_to_face_filter_for_other_advice_types_spec.rb
spec/features/landing_phone_or_online_filter_for_other_advice_types_spec.rb
spec/features/results_face_to_face_filter_for_other_advice_types_spec.rb
spec/features/results_phone_or_online_filter_for_other_advice_types_spec.rb

Found another instance of this failure by accident. Also spotted 2 other tests which would be susceptible so fixed them too.

[DEV APPROVED] Fix test failure due to string sorting '10' before '9'

---

spec/features/landing_face_to_face_filter_for_other_advice_types_spec.rb
spec/features/results_face_to_face_filter_for_other_advice_types_spec.rb

When fixing the ascii ordering bug before, I applied the same fix to
other tests that looked susceptible to the same error. Except I didn't
read the name of the tests and so didn't notice that 2 of the 4 order by
location and don't need the ordering fix :S
The magic seed that revealed this error was `rspec --seed 52482`

Revert fixes to tests that order by location

---

Gemfile
Gemfile.lock
db/schema.rb
spec/features/consumer_views_a_search_result_spec.rb

This change fixes tests broken as a consequence of https://github.com/moneyadviceservice/rad/pull/318.

[DEV APPROVED] Firm email and tpnum have been removed

---

app/views/search/partials/_firm.html.erb

Little PR to remove the hyperlink to a firm's currently non-existant profile page.

Disable dead link to firm profile from result heading

---

app/helpers/remote_search_helper.rb

Removing a helper that is no longer in use since https://github.com/moneyadviceservice/rad_consumer/commit/85e5d7295d503ac637cd5b57a630af1f036dd45c

remove helper that is no longer used.

---

app/views/firms/partials/_firm_details.html.erb

It appears that in the eager refactoring of the profile map into a helper method (`firm_map_component`), a trailing `</div>` was left behind. This was breaking the behaviour of the dough tabs used on the page. Also fixed up the indentation while I was in here.

remove extra div, fix indentation

---

app/controllers/firms_controller.rb
app/views/firms/partials/_content.html.erb
app/views/firms/partials/_firm_details.html.erb
app/views/firms/partials/_header.html.erb
app/views/firms/show.html.erb
spec/controllers/firms_controller_spec.rb

If a user performs a 'remote' search, they haven't provided any location information.
We should only show distance to nearest adviser and the map when viewing a firm's profile if the user performed a search which provides location data.
* Adds assignment to existing `SearchForm` in the controller
* Update views with conditionals to display location information if appropriate search type.

[DEV APPROVED]Only show location / map information if it's an 'in-person' search

---

app/views/firms/partials/_advisers.html.erb
app/views/firms/partials/_content.html.erb
config/locales/en.yml

This PR removes a dough tab from the firm profile page. The 'Adviser' tab was in previous designs when the profile was first worked on before being shelved for a period of time. Current designs no longer include this tab.
**Before**
**After**

[DEV APPROVED] Remove 'Advisers' tab

---

app/views/firms/show.html.erb
config/locales/cy.yml
config/locales/en.yml

This PR reuses an existing translation key for page titles, as it consistent across all the pages. I've also added missing Welsh keys for the firm profile page, as they appear to have been missed off when the profile was previously started. We've not requested translations yet, but it seemed a good idea to at least have the placeholders in the codebase so they aren't forgotten about.

[DEV APPROVED] add placeholders for welsh translations / use existing page_title

---

app/views/firms/partials/_header.html.erb

Wrap each of the methods of contacting a firm in a conditional to only render them if there is actually data for the contact method.
e.g. Having removed the website for a firm, before this change all three contact links would appear: 
When in reality, the user should only see two:

[DEV APPROVED] only render telephone, email, and website if they exist

---

.rubocop.yml
Gemfile
Gemfile.lock
app/assets/stylesheets/components/_search_filter.scss
app/forms/search_form.rb
app/serializers/search_form_serializer.rb
app/views/search/partials/_search_filter.html.erb
app/views/search/partials/filters/_pension_pots.html.erb
app/views/search/partials/filters/_qualifications_and_accreditations.html.erb
config/locales/cy.yml
config/locales/en.yml
spec/features/results_filter_on_quals_and_accreds_spec.rb
spec/fixtures/vcr_cassettes/qualifications_and_accreditations_filters_on_results_list.yml
spec/forms/search_form_spec.rb
spec/serializers/search_form_serializer_spec.rb
spec/support/search_form_section.rb

Adds in a results page filter to reduce results based on which qualifications a firm's advisers have.
It is expected that the primary users of this will be more specialist such as the Citizens Advice Bureau making a search for a member of the public. They will be more informed about what the qualifications mean.
* Qualifications and accreditations are configured in two separate database tables. But here we need to merge and present the combined set in one select list.
* `Accreditation#order` and `Qualification#order` are pre-existing fields intended to be consistent/static ids that can be used to refer to specific records regardless of what Postgres id has been assigned.
* Several classes are near to or over the 100 line max class length limit imposed in Rubocop by default. Here I have …

[DEV APPROVED] Qualification accreditation filters

---

Gemfile
Gemfile.lock
app/assets/stylesheets/_enhanced.scss
app/assets/stylesheets/_settings.scss
app/assets/stylesheets/components/_types_of_advice.scss
app/helpers/firm_helper.rb
app/views/firms/partials/_firm_details.html.erb
config/locales/cy.yml
config/locales/en.yml
spec/helpers/firm_helper_spec.rb

Adds the 'Types of advice offered' section to the firm profile.

Types of advice

---

app/assets/stylesheets/components/_accreditation.scss
app/assets/stylesheets/components/_firm.scss
app/assets/stylesheets/layouts/_firm.scss
app/views/firms/partials/_firm_details.html.erb
config/locales/cy.yml
config/locales/en.yml

It's been a while since I had to BEM. I hope I've got the right split between `.l-*` and BEM components. Happy to be guided to a better way. E.g. is this the best way to implement `.firm__divider`? It doesn't feel 100% right to me?
Discovered the how the `@include row(n)` mixin can be used to collapse unwanted gutters in nested grid cols/rows. So applied that using the new `.l-firm__row` class.

[DEV APPROVED] Add accreditation/qualifications to the profile screen

---

app/views/firms/partials/_firm_details.html.erb

Don't render the dividing line when there are no logos

---

app/assets/javascripts/modules/FirmMap.js

Small PR to remove the title from appearing when hovering over an adviser pin (see image for example of old behaviour)

don't display a title for the map markers

---

app/assets/javascripts/require_config.js.erb
config/initializers/assets.rb

In development this isn't a visible issue, but deploying to staging. RSVP isn't available, which in turn causes a JavaScript error as DoughBaseComponent has a dependency on it. This change ensures that it is available in non development ENVs

add rsvp to requirejs config

---

config/locales/en.yml

This PR is in place to allow us to preview the new tooltip to the business on a demo server.
Once they are happy with the text in-situ on the page we'll request and add the welsh translations.

Updating english tooltip text on firm profile page

---

app/assets/javascripts/modules/FirmMap.js
app/helpers/application_helper.rb
app/views/firms/partials/_firm_details.html.erb

Another map/pin related PR... This wasn't picked on before as we never had the profile deployed to the demo server. The pin marker images are held within `app/assets`, so we need to use `image_path` to ensure we have the assets available.

ensure the pins will be displayed

---

app/views/firms/partials/_header.html.erb

Pressing this button ...
... will now open the page in a new tab/window as indicated by the contained icon.

[DEV APPROVED] Profile 'Website' button should open link in a new window

---

Gemfile
Gemfile.lock
app/helpers/firm_helper.rb
app/views/firms/partials/_firm_details.html.erb
config/locales/cy.yml
config/locales/en.yml
spec/helpers/firm_helper_spec.rb

When the smallest pot size considered by a firm is 'Under £50k' it now shows:
otherwise it shows the value

On the profile page when the firm has a minimum pot size of 'Under £50k' display the text 'No minimum pot size'

---

app/assets/stylesheets/layouts/_firm.scss
app/views/firms/partials/_guide_link.html.erb
app/views/firms/partials/_profile_help.html.erb
app/views/firms/show.html.erb
app/views/search/partials/_search_filter.html.erb
config/locales/cy.yml
config/locales/en.yml

This adds some help text to the search filter and the profile page. We are awaiting Welsh translations but will raise a separate PR for those when they come through. In the meantime we need to put this through the QA process.

Profile and filter copy

---

app/assets/stylesheets/components/_firm.scss
app/views/firms/partials/_header.html.erb
config/locales/cy.yml
config/locales/en.yml
spec/support/results_page.rb

Hi. Sorry this is a mixed set of things that we needed to change after our Friday demo that we need done for our release today. Have tried to make it easier with screen shots.

Mixed bag of UI changes post-demo

---

app/assets/stylesheets/_settings.scss
app/assets/stylesheets/components/_firm.scss
app/assets/stylesheets/components/_keyword.scss
app/assets/stylesheets/components/_result.scss

The border and drop shadow on the profile page was darker than on the results page. This makes them consistent across pages.

[DEV APPROVED] Changing border and shadow to match results page

---

app/assets/stylesheets/components/_firm.scss
app/assets/stylesheets/layouts/_firm.scss
app/views/firms/show.html.erb

Reduces the amount of whitespace on the top heading to be inline with the heading size on the results page.
Balance the whitespace between the header, back link, and the page content
**before**
**after**

[DEV APPROVED] adjust whitespace/padding around profile heading

---

app/assets/stylesheets/components/_callout.scss
app/assets/stylesheets/components/_types_of_advice.scss
app/views/firms/partials/_firm_details.html.erb

Reduces the whitespace between "Firm's services" and "Types of advice offered" to match the whitespace between the top heading and the map.
**before**
**after**

[DEV APPROVED] reduce whitespace to match spacing further up

---

app/assets/stylesheets/components/_firm.scss
app/views/firms/partials/_header.html.erb

When viewing a profile page from an 'in-person' search, the buttons that appear for the phone, website, and email should not be displayed in the 'header' area. This information will be displayed directly next to each office in the offices tab.
For profiles from 'phone or online', they should be retained.
**'in-person' profile.**
**'phone or online' profile.**

[DEV APPROVED] only display the buttons if it's a remote search

---

app/assets/stylesheets/components/_firm.scss
app/assets/stylesheets/layouts/_firm.scss
app/views/firms/partials/_content.html.erb
app/views/firms/partials/_profile_help.html.erb

There are two types of search within rad consumer: 'in-person', and 'phone or online only'. In the case of it being phone or online only, the office information isn't to be displayed and subsequently, the dough tabs at the top of the page shouldn't appear either.
**profile when from a 'in-person' search result**
**profile when from a 'phone or online only' search result**

[DEV APPROVED] don't display tabs when searching for online and telephone advice (remote). fix whitespace.

---

app/assets/stylesheets/_enhanced.scss
app/assets/stylesheets/_settings.scss
app/assets/stylesheets/components/_firm.scss
app/assets/stylesheets/components/_investing.scss
app/helpers/firm_helper.rb
app/views/firms/partials/_firm_details.html.erb
config/locales/cy.yml
config/locales/en.yml
spec/helpers/firm_helper_spec.rb

Adds the **Other services** section to the firm profile, which can include Sharia or ethical investments. 
Also corrected the colour used as a divider between sections as it was slightly darker than the designs we're working with. So it now matches the border colour.

[Dev approved] Add sharia ethical investing

---

app/assets/javascripts/modules/FirmMap.js
app/assets/stylesheets/components/_firm.scss
app/assets/stylesheets/states/_is_hidden.scss
app/views/firms/partials/_content.html.erb
app/views/firms/partials/_firm_details.html.erb

complimentary work to https://github.com/moneyadviceservice/mas-rad_core/pull/126. Adds the office markers to the map (note: using dummy data in pic below)
Additionally, we've added some additional styling to improve the appearance of the profile page when javascript is disabled. Previously the map would not render, but the space for it, the heading, and a list of advisers would appear making the page difficult to understand.

[DEV APPROVED] Add offices to map

---

app/assets/javascripts/modules/FirmMap.js

We don't bind to the click event on a google maps marker, so setting `clickable: false` will stop the cursor changing from 'grab' to 'pointer', which we don't want.

stop markers changing the cursor from "grab" to "pointer"

---

app/views/firms/partials/_offices.html.erb

:county is optional in the model. Currently when this is blank/nil we display a trailing ','
The PR removes that scenario from the UI.
Previously with a nil county
With fix in place:

[DEV APPROVED] Do not display county of address if it is nil

---

app/assets/javascripts/modules/FirmMap.js
app/helpers/office_helper.rb
app/views/firms/partials/_firm_details.html.erb
spec/helpers/office_helper_spec.rb

Enables only office pins to display address details on the map using a google map 'InfoWindow'

[DEV APPROVED] display office addresses when their pins are clicked

---

app/views/firms/partials/_header.html.erb

For firms that offer face-to-face advice and therefore have an offices tab in their profile (with contact details shown in it) we experimented with hiding the contact details in the profile header. But decided that it was better to show them.
So goes from:
to ...
Now for all firms (both face-to-face advice and remote advice firms)

Always show the contact details of the firm in the profile header

---

spec/features/results_filter_on_quals_and_accreds_spec.rb
spec/support/elastic_search_helper.rb

Based on recent changes, the job class is no longer being used and will be removed. So removing a reference to it here in favour of a higher-level call.

Remove reference to IndexFirmJob

---

app/assets/stylesheets/components/_result.scss

Re-introduces $baseline-unit margin between two elements which appears to have been removed at some point.
**before**
**after (original design)**

[DEV APPROVED] insert baseline margin-top

---

app/assets/stylesheets/_enhanced.scss
app/assets/stylesheets/components/_button.scss
app/views/layouts/application.html.erb

There is a button for a newsletter that appears at the bottom of all pages. This PR changes the button to use the normal white-space property so text wraps within the element, rather than the element spilling over other text/links.
**before**
**after**

add style to set "white-space" to be normal for button in footer

---

app/controllers/firms_controller.rb
app/views/firms/partials/_content.html.erb
app/views/firms/partials/_firm_links.html.erb
app/views/firms/partials/_header.html.erb
app/views/firms/partials/_offices.html.erb
lib/geosort.rb
spec/controllers/firms_controller_spec.rb
spec/features/firm_profile_for_in_person_search_spec.rb
spec/fixtures/vcr_cassettes/firm_profile_for_in_person_search.yml
spec/lib/geosort_spec.rb
spec/support/office_section.rb
spec/support/profile_page.rb

Bit of a heavy PR for what is a relatively minor thing in the UI...
In summary:
* When viewing the offices tab for a given firm, all of the offices are sorted by location relative to the initial postcode the user searched with.
* If it is a postcode search, the main links at the top of the profile should be for the telephone, email, and website of the nearest office, rather than the main office.

Order offices by distance

---

app/controllers/search_controller.rb
app/forms/search_form.rb
app/serializers/search_form_serializer.rb
spec/features/consumer_searches_remote_advice_spec.rb
spec/serializers/search_form_serializer_spec.rb

> Currently, remote firms are shown alphabetically in the search results.  As most users do not click beyond the first results page, randomization of results would provide a fairer display to firms appearing at the end of the alphabet. 
Randomises the search results for phone/online only firm searches. Uses a randomly generated seed value for the search, which is persisted between requests for an individual user. This ensures that the user doesn't see the search results change between each request (if they go back/forward between the search results page).

Randomise firm search results

---

spec/features/results_phone_or_online_filter_for_other_advice_types_spec.rb

Due to the introduction of randomised search results, there's now an error that sometimes appears in spec/features/results_phone_or_online_filter_for_other_advice_types_spec.rb.
Essentially we no longer need to worry about which order they are returned in, so test adjusted accordingly.

Remove assertion on result order

---

Gemfile
Gemfile.lock
app/helpers/firm_helper.rb
app/views/firms/partials/_firm_links.html.erb
db/schema.rb
spec/helpers/firm_helper_spec.rb

> if a firm enter their website address in the following format: www.mywebsite.com an error message displays stating the firm should enter the address using this format: http://www.mywebsite.com
>
> The sign-up process can be simplified by allowing firms to enter their website with this format:
> www.mywebsite.com
Related PRs https://github.com/moneyadviceservice/rad/pull/333 and https://github.com/moneyadviceservice/mas-rad_core/pull/139
For this repository this meant updating to the latest version of rad-core, and if the protocol is not in the website address, adding it to the link (this is so that links actually go to the external site).
Link would go to `/example.com`
Link goes to `http://example.com`

[DEV APPROVED] Firm website URL format: ensure external links have protocol

---

app/assets/stylesheets/layouts/_results.scss
app/views/search/partials/_results.html.erb
config/locales/cy.yml
config/locales/en.yml

Add the line "Firms presented in no particular order" on the 'online or remote' search results page.
Because the results are now returned in a random order to get rid of alphabetical sort bias.

State sort order on remote-advice search results page

---

app/helpers/firm_helper.rb
app/views/firms/partials/_firm_details.html.erb
config/locales/cy.yml
config/locales/en.yml
spec/helpers/firm_helper_spec.rb

Show firm languages on the RAD directory

---

app/assets/stylesheets/_enhanced.scss
app/assets/stylesheets/_settings.scss
app/assets/stylesheets/components/_advice_method.scss
app/assets/stylesheets/components/_firm.scss
app/assets/stylesheets/components/_investing.scss
app/assets/stylesheets/components/_plain_list.scss
app/assets/stylesheets/components/_types_of_advice.scss
app/helpers/firm_helper.rb
app/views/firms/partials/_firm_details.html.erb
spec/helpers/firm_helper_spec.rb

* Set a default text colour for the firm details tab and reduce the number of places it gets redefined.
* Replace the `investing__*` styles with something more generic that makes sense to use on the language list too, `firm__service-heading`
* Create a general plain vertical list style that can be shared between the three places that use it.

Firm CSS refactor

---

config/locales/cy.yml
config/locales/en.yml

MAS comms style dictates we use the version of the word _'sharia'_ without an _'h'_ at the end.
(Related PR to make RAD consistent too is here: https://github.com/moneyadviceservice/rad/pull/336)

[DEV APPROVED] Drop the 'h' from the end of 'sharia' and the hyphen from the sentence

---

Gemfile
Gemfile.lock
config/locales/cy.yml
config/locales/en.yml
db/schema.rb

Related PRs: https://github.com/moneyadviceservice/rad/pull/342 and https://github.com/moneyadviceservice/mas-rad_core/pull/145
The '5' in the locale files are referring to the "Other" accreditation.

[DEV APPROVED] Remove "Other" accreditation: consumer side

---

app/views/layouts/application.html.erb
config/locales/cy.yml
config/locales/en.yml

This PR is to update the site-wide breadcrumbs:
to look like the breadcrumbs below with text and links updated in english and welsh

[DEV APPROVED] Updating breadcrumbs

---

app/assets/stylesheets/layouts/_header.scss
app/views/layouts/application.html.erb
app/views/shared/_header.html.erb

Similiar to the PR raised for the self-service portion of RAD https://github.com/moneyadviceservice/rad/pull/375, the header was not appearing in IE8.
* Fixes the `<header>` element to properly display as a `block`.
* Refactors the header out into a shared partial so `rad` and `rad_consumer` share the same pattern for template abstraction.
* The main website and RAD use a PNG image for the main brand logo. RAD consumer was using an SVG, and subsequently not rendering correctly in IE8 after the header was correctly displaying as a block. Taking a look side by side, there was a difference between the two images. I've switched the image asset to be the PNG file the same as `frontend` for consistency.
*mismatch of png + svg between browsers*
*IE8 after fixes (self service left, directory …

fix header in ie8

---

app/views/layouts/application.html.erb

Replacing asset urls from Rackspace CDN, to the new Azure CDN. (Same as https://github.com/moneyadviceservice/rad/pull/380)
_NOTE:_ There are four PDF files that appear to have been manually uploaded to the CDN which are not being changed as part of this PR. @slaywell has updated a card in the MAS backlog to include changing these over as it involves some manual intervention to make it happen.
```
https://fedb5feb4c074be48b1a-7d2b925ab3869b76f1d9fad9b2ecd2bb.ssl.cf3.rackcdn.com/rad_expert_transcript.cy.pdf
https://fedb5feb4c074be48b1a-7d2b925ab3869b76f1d9fad9b2ecd2bb.ssl.cf3.rackcdn.com/rad_customer_transcript.cy.pdf`
https://fedb5feb4c074be48b1a-7d2b925ab3869b76f1d9fad9b2ecd2bb.ssl.cf3.rackcdn.com/rad_expert_transcript.en.pdf
https://fedb5feb4c074be48b1a-7d2b925ab3869b76f1d9fad9b2ecd2bb.s …
```

update site assets to point to azure cdn

---

app/assets/stylesheets/_enhanced.scss
app/assets/stylesheets/_settings.scss
app/assets/stylesheets/components/_recently_viewed.scss
app/controllers/firms_controller.rb
app/helpers/firm_helper.rb
app/models/recently_visited_firms.rb
app/views/firms/partials/_header.html.erb
app/views/firms/partials/_profile_help.html.erb
app/views/firms/partials/_recently_visited.html.erb
app/views/search/partials/_firm.html.erb
app/views/search/partials/firm/_adviser_distance.html.erb
config/locales/cy.yml
config/locales/en.yml
spec/controllers/firms_controller_spec.rb
spec/helpers/firm_helper_spec.rb
spec/models/recently_visited_firms_spec.rb

The PR is to add a list of Recently Visited Firms to the firm profile page.
We were asked to display up to 3 previous firms.
If the firm was remote, not to display any distance info.
If currently viewing a firm that is in the list, then don't display it in the recently used firms list. Looking at the screenshot you can see we are viewing Test 01 Firm, however this is excluded from the Recently Viewed Firms.

[DEV APPROVED] [AWAITING WELSH TRANSLATIONS] Recently visited firms

---

app/views/layouts/application.html.erb

Requires IE to use the latest version, as per  `frontend`.
See http://twigstechtips.blogspot.co.uk/2010/03/css-ie8-meta-tag-to-disable.html

Add meta tag to force IE out of compatibility mode

---

app/views/layouts/application.html.erb

When migrating CDN we grabbed the wrong version of the assets.
This PR maintains the new CDN, and reverts to the old version of the assets.
Before:
After:

Pointing CDN to older version of assets on CDN

---

Gemfile
Gemfile.lock
app/assets/stylesheets/_enhanced.scss
app/assets/stylesheets/_settings.scss
app/assets/stylesheets/components/_adviser.scss
app/assets/stylesheets/components/_firm.scss
app/assets/stylesheets/layouts/_adviser.scss
app/controllers/firms_controller.rb
app/helpers/firm_helper.rb
app/views/firms/partials/_advisers.html.erb
app/views/firms/partials/_content.html.erb
bower.json.erb
config/locales/cy.yml
config/locales/en.yml
lib/geosort.rb
spec/controllers/firms_controller_spec.rb
spec/features/firm_profile_advisers_tab_spec.rb
spec/fixtures/vcr_cassettes/firm_profile_advisers_tab.yml
spec/helpers/firm_helper_spec.rb
spec/lib/geosort_spec.rb
spec/support/adviser_section.rb
spec/support/profile_page.rb

This PR adds a tab listing advisers on a firm's profile page. When doing a postcode search each adviser has the distance listed, and a stripped version of the postcode, and they are sorted nearest first. 
FYI there are a few welsh translations that we are waiting on.
When doing a remote search, no distance or postcode are listed and the advisers are sorted alphabetically. 
We also reuse a Dough component to 'Show more advisers'. The first 10 are visible when the page first appears.

Advisers tab on the firm profile page

---

app/views/search/partials/filters/_qualifications_and_accreditations.html.erb
app/views/shared/_further_info_trigger.html.erb
config/locales/cy.yml
config/locales/en.yml

This is a small PR to update the label on the Accreditation and Qualification filter and added a tooltip link.
We are currently waiting on the welsh translation to arrive.
Before: 
After:

Updating Accreditation and Qualification label and adding tooltip link

---

app/helpers/firm_helper.rb
app/views/firms/partials/_recently_visited.html.erb
spec/helpers/firm_helper_spec.rb

When visiting a firm profile page, we were excluding that firm form the recently visited firm list
As the list is only shown on firm profile pages this means that at most only 2 firms will be displayed, when we are supposed to display 3.
This PR removes the logic that hides the current firm from the list.

Stop hiding current firm in recently viewed firms list

---

Gemfile
Gemfile.lock
app/assets/stylesheets/_enhanced.scss
app/assets/stylesheets/components/_icon.scss
app/assets/stylesheets/layouts/_header.scss
app/views/layouts/application.html.erb
app/views/shared/_header.html.erb

Brings this app up to date with the frontend and the latest Dough.
* Swaps to using tags to track versions of Dough so it's easy to see the exact version we are referencing.
* Yeast is still configured to track master in bower.json.erb so all fresh deployments naturally get the latest version anyway.
* Updated the URLs for assets we import from frontend via the CDN by looking at the page source for http://www.moneyadviceservice.org.uk today.
* Made changes necessary to integrate [social icon updates](https://github.com/moneyadviceservice/frontend/pull/1256) and the new [mobile sticky header](https://github.com/moneyadviceservice/frontend/pull/1365). 
Broadly tested using BrowserStack on:
* IE8, IE11
* iPhone 6, iPad
* Galaxy S6
* FF latest
* Safari latest
* Chrome latest
:point_up:  The …

Consumer App: Upgrade to dough 5.12 and integrate latest frontend CSS from the CDN

---

app/assets/stylesheets/_enhanced.scss
app/assets/stylesheets/_settings.scss
app/assets/stylesheets/components/tab_selector.scss

The PR is to stop wrapping of tabs on mobile :point_down: 
Now, when entering mobile sized screens buttons are presented rather than tabs.
When loading the page, Dough arrives first with it's tab styling.
Progressive enhancement is somewhat curtailed by having the desktop styling already in place.
To make this work we took the following approach: (and ordered the scss file in the same manner for clarity)
1: Undo/Nullify the dough styling
2: Add mobile styling
3: Add > mobile styling
This is very clunky and any feedback would be appreciated.

Restyle tabs for mobile

---

Gemfile
Gemfile.lock
app/forms/search_form.rb
app/views/firms/partials/_firm_details.html.erb
config/locales/cy.yml
config/locales/en.yml
db/schema.rb
spec/forms/search_form_spec.rb

Building on the work in this [mas-rad_core PR](https://github.com/moneyadviceservice/mas-rad_core) and [RAD PR](https://github.com/moneyadviceservice/rad)
This PR allows users to filter on :non_uk_residents and also updates the firm profile page if the firm provides this service.
We are currently awaiting final copy on the filter label, checkbox text and tooltip, there after we'll request the welsh translation of the copy.

Add non uk residents filter

---

app/forms/filters/advice_method.rb
app/forms/filters/language.rb
app/forms/filters/pension_pot.rb
app/forms/filters/qualification_or_accreditation.rb
app/forms/filters/service.rb
app/forms/filters/type_of_advice.rb
app/forms/search_form.rb
app/views/firms/partials/_firm_details.html.erb
app/views/search/partials/_search_filter.html.erb
app/views/search/partials/filters/_workplace_financial_advice.html.erb
config/locales/cy.yml
config/locales/en.yml
db/schema.rb
spec/forms/search_form_spec.rb

Building on the work in this [mas-rad_core PR](https://github.com/moneyadviceservice/mas-rad_core/pull/152) and [RAD PR](https://github.com/moneyadviceservice/rad/pull/387)
This PR allows users to filter on :workplace_financial_advice and also updates the firm profile page if the firm provides this service.
We are currently awaiting final copy on the filter label, there after we'll request the welsh translation of the copy.

[DEV APPROVED]Add workplace advice filter

---

app/helpers/firm_helper.rb
spec/helpers/firm_helper_spec.rb

In a previous PR we added Workplace financial advice and Non UK residents to the firm profile page.
I didn't notice a conditional wrapping this in the view, which needs to know if Workplace financial advice or Non UK residents are set. This PR updates the : firm_has_investing_types? method that the conditional calls.

[DEV APPROVED] Making conditional smarter to display Other Services

---

app/helpers/firm_helper.rb
app/views/firms/partials/_firm_details.html.erb
config/locales/cy.yml
config/locales/en.yml
spec/helpers/firm_helper_spec.rb

When this corner of the UI first got created it was genuinely just about investing options. It's scope has now widened so it's now time to rename things in the code to reflect this.

Rename helper and locale keys

---

app/models/rad_consumer_session.rb
spec/models/rad_consumer_session_spec.rb

We noticed a bug where the back link in the firm profile page wasn't returning us to the most recent search. This change fixes that.
There is a guard condition that used to short-circuit the `#store` method if the firm being visited was already in the list of most recently visited firms.
Unfortunately update of the most recent search URL was happening after this guard condition.
So this change separates out the logic for the two concerns so they cannot affect each other anymore.

Always update the search url cache in the session store

---

README.md
app/assets/stylesheets/_enhanced.scss
app/assets/stylesheets/components/_footer-primary.scss
app/views/layouts/application.html.erb
config/locales/cy.yml
config/locales/en.yml

[Ticket 7328](https://moneyadviceservice.tpondemand.com/entity/7328) involves removing the MAS newsletter section from the RAD footer:
Whilst making the changes, we had setup issues with Elasticsearch so this PR also contains some extra steps in the Readme to avoid these problems (cc @munckymagik @JiggyPete).

[DEV APPROVED] 7328 - Removing newsletter from footer and updating readme

---

app/views/firms/partials/_firm_details.html.erb

Redeye has run an AA test on the firm details page on RAD to see if there is an increase in interaction if the map is moved under the text. The test has proven to be positive.
Currently, the map is above the text which provide firms details.
| Before | After |
|--------|------|
|![image](https://cloud.githubusercontent.com/assets/13165846/19303770/da3e4aae-9061-11e6-8748-0780bd6c6f9b.png)|![image](https://cloud.githubusercontent.com/assets/13165846/19303716/b17cf11a-9061-11e6-95f2-d145c9d257ea.png)|

[DEV APPROVED] 7670 - Switching map and details panels on firm page

---

app/helpers/search_helper.rb

This amends the link to the Glossary from (for instance)
- 'https://directory.moneyadviceservice.org.uk/en/firms/glossary/#chartered_fp' to 
- 'https://directory.moneyadviceservice.org.uk/en/glossary/#chartered_fp'
i.e. from .../en/... not .../en/firms/...

[DEV APPROVED] TP: 7733, Comment: Amend wrong URL

---

app/views/search/partials/filters/_advice_method.html.erb
config/locales/cy.yml
config/locales/en.yml

In the previous PR (https://github.com/moneyadviceservice/rad_consumer/pull/309) I did not add a Welsh translation for "Please make a selection", this has now been provided and added to the project.
| English | Welsh |
|--------|--------|
|<img src="https://cloud.githubusercontent.com/assets/13165846/20793732/6faa0bb6-b7c0-11e6-89a5-bc943435a0b1.png" width="300" />|<img src="https://cloud.githubusercontent.com/assets/13165846/20793751/8f6f12e8-b7c0-11e6-91fd-a4270e2d9c4d.png" width="300" />|

[DEV APPROVED] - 7756 - Adding welsh translation to option select validation

---

Gemfile
Gemfile.lock
app/controllers/firms_controller.rb
app/models/rad_consumer_session.rb
app/presenters/recently_visited_firm.rb
app/views/firms/partials/_recently_visited.html.erb
spec/controllers/firms_controller_spec.rb
spec/features/search_by_firm_name_spec.rb
spec/fixtures/vcr_cassettes/search_by_firm_name.yml
spec/models/rad_consumer_session_spec.rb
spec/presenters/recently_visited_firm_spec.rb
spec/support/firm_section.rb
spec/support/landing_page.rb

Before the code was using searching for all firms
passing the _id as search all.
Changing to just find the specific id solves the issue.
But generates another problem. The reason that the code
does a search all is because elastic search returns a
_score attribute with the distance as the value from
where the user is located.
This PR includes the fix bug on the recently firms visited sidebar
When user search by name the app should not pass any information
of the near adviser (because the user did not provide any location).
The logic is not using the elastic feature anymore, it is relying on the
Geosort module to get the nearest adviser to show the message
on the sidebar.
**Disclaimer: The Gemfile are using a local mas-rad-core until this PR is merged: …

7873 - Find firm by id on elastic search

---

README.md

The links to our WIKI pages for setting up the database and elasticsearch locally point to pages which no longer exist. This pr updates those links.

[DEV APPROVED] Update links to MAS wiki pages

---

README.md

On creating new tests, it was difficult to find where the test data was being created. This pr adds a pointer in the readme to the mas-rad_core factories.

[DEV APPROVED] - Include dependency on mas-rad_core

---

Gemfile
Gemfile.lock
app/helpers/office_helper.rb
app/views/firms/partials/_firm_links.html.erb
app/views/firms/partials/_header.html.erb
app/views/firms/partials/_offices.html.erb
config/locales/cy.yml
config/locales/en.yml
db/schema.rb
spec/features/firm_profile_for_in_person_search_spec.rb
spec/helpers/office_helper_spec.rb
spec/support/profile_page.rb

This pr addresses [user story 7929](https://moneyadviceservice.tpondemand.com/restui/board.aspx?acid=f363bea37e60ac292c07aaf8b50f0da9#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&boardPopup=userstory/7929/silent)
It needs to be deployed in conjunction with [mas-rad_core#162](https://github.com/moneyadviceservice/mas-rad_core/pull/162) and builds on [rad#401](https://github.com/moneyadviceservice/rad/pull/401) which created the ability for admin users to add a specific website for a firm's office.

[DEV APPROVED] - 7929 expose office website

---

spec/support/profile_page.rb

I was having this error on Linux when running rspec:
`Uninitialized Constant (NameError)` for OfficeSection and AdviserSection in ProfilePage. Sorting the files when required on `spec_helper.rb` fixed it and it should now have the same behavior on different systems.

[DEV APPROVED] Require OfficeSection and AdviserSection manually on ProfilePage in specs so they're available

---

app/views/layouts/application.html.erb

the current web chat link on RAD opens the default WhosOn branded web chat windows, this change adds the sWOChatStart variable to the application for the webchat.js script so the web chat link on RAD opens the new Mas branded chat window

8462 change webchat to load new chat window

---

.travis.yml

The build is not working in Travis. We found this issue while working on #324 and fixed it there but that branch won't be merged.
**Reason**
Travis is rolling out a newer version of Ubuntu, the Elasticsearch version is probably different because search results are returning nil. This is the message for failing builds:
>This job ran on our Trusty environment, which is gradually becoming our default Linux environment. Read all about this [in our blog: Trusty as a default Linux is coming](https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming?utm_source=web&utm_medium=banner&&utm_campaign=trusty-default) and take note that you can add `dist: precise` in your .travis.yml file to continue using Precise.

[DEV APPROVED]Set Ubuntu version to Precise for Travis

---

app/views/search/partials/firm/_adviser_distance.html.erb

[TP Link](https://moneyadviceservice.tpondemand.com/entity/7957)
The pin image on search results next to "has an adviser X miles away" is being read as "image" for VoiceOver users, which is confusing. Since the image is not required and the text surrounding it is sufficient, `aria-hidden=true` was added to hide it from screen readers.

[DEV APPROVED] 7957 - Add aria-hidden property to svg icon to hide from VoiceOver

---

app/views/search/partials/filters/_advice_method.html.erb

[TP Link 1963](https://moneyadviceservice.tpondemand.com/entity/7963)
[TP Link 1964](https://moneyadviceservice.tpondemand.com/entity/7964)
**Summary**
*How would you like to receive  advice?* search filter: When navigating out of context to read the buttons, the search button says ‘or search button.’ ‘Search button’ is clearer.  Consider removing the ‘or’ from the options as this is not really required.
**Solution**
When just removing the `<h3>` text, we have some spacing issues:
On the "Phone or Online" option the `margin-bottom` property is being set to `0`. This is coming from dough because this is a `form__group-item:last-child` element. It doesn't happen with "In Person" and "Search for a firm by name" because they have an extra hidden `form__group-item` element each to input a …

[DEV APPROVED]7963, 7964 - Accessibility: Remove 'or' heading from search filter

---

app/assets/stylesheets/components/_search_filter.scss
app/assets/stylesheets/layouts/_landing_page.scss
app/views/landing_page/_search_filter.html.erb
app/views/landing_page/show.html.erb

TP Links:
[7958](https://moneyadviceservice.tpondemand.com/entity/7958)
[7969](https://moneyadviceservice.tpondemand.com/entity/7969)
This addresses an accessibility problem flagged up in 7958: all `<fieldset>` elements must have a `<legend>` element as their first child. Semantically what was previously an `<h2>` tag should be a `<legend>`.
This also addresses an accessibility issue from 7969, that the ‘help’ icon should not be part of a heading tag. 
Previous conversation: #327

[DEV APPROVED] 7958, 7969 - Add legend to advice search form for assistive technologies

---

app/assets/stylesheets/components/_outline_button.scss

[TP link](https://moneyadviceservice.tpondemand.com/entity/7971)
**Summary**
This is an accessibility requirement. The telephone link on the firms#show page were underlined on hover, but unchanged on focus. Keyboard-only users who navigate using the tab key need visual feedback when a link has focus, so this was flagged up as confusing in the accessibility review. This has been fixed by giving these links underlining on focus as well.

[DEV APPROVED] 7971 - Underline telephone links on focus as well as hover

---

app/forms/filters/pension_pot.rb
app/views/application/_further_info_trigger.html.erb
app/views/application/_search_button.html.erb
app/views/kaminari/_next_page.html.erb
app/views/kaminari/_prev_page.html.erb
spec/forms/search_form_spec.rb

[TP link](https://moneyadviceservice.tpondemand.com/entity/7972)
**Summary**
Two accessibility improvements that were suggested in an accessibility review.
1. SVG elements inside a link or button receive focus independently of the link/button in Internet Explorer. This is confusing for keyboard-only users. Setting `focusable="false"` on the SVG fixes this.
2. A select list had the default option at the bottom. Keyboard-only users expect the default value to be at the top and the others below. We have changed the order of the options to fix this.

[DEV APPROVED] 7972 - Accessibility fixes

---

app/views/landing_page/show.html.erb
config/locales/cy.yml
config/locales/en.yml

[TP Link](https://moneyadviceservice.tpondemand.com/entity/7959)
This was reported as an accessibility issue, iframes should be properly labeled for screen readers.

[DEV APPROVED] 7959 - Add title to YouTube videos iframes for screen reader users to understand

---

public/browserconfig.xml

[TP Link](https://moneyadviceservice.tpondemand.com/entity/8367)
From [Rollbar](https://rollbar.com/rad-consumer-production/rad-consumer-production/items/2/), requests to `/browserconfig.xml` trigger a 404. This is a configuration file Internet Explorer 11 (and presumably Edge) use:
>Browser configuration files (also known as browserconfig) can be used to define pinned site customizations, such as tile backgrounds, badge updates, and tile notifications.
[More information](https://msdn.microsoft.com/library/dn320426(v=vs.85).aspx)
The PR adds an empty `browserconfig.xml` file to avoid the 404. Do we want a proper browserconfig file for pinning the site in Windows devices? There's an online tool by Microsot to create this file: http://www.buildmypinnedsite.com/

[DEV APPROVED] 8367 - Add browserconfig.xml file for IE 11 and Edge

---

app/assets/stylesheets/components/_icon.scss
app/views/application/_further_info_trigger.html.erb
app/views/landing_page/_search_filter.html.erb
app/views/landing_page/show.html.erb
app/views/search/partials/filters/_qualifications_and_accreditations.html.erb
config/locales/cy.yml
config/locales/en.yml

[TP Link](https://moneyadviceservice.tpondemand.com/entity/7960)
**Summary**
Links were found that took users to different locations whether it be another page or opening a pop up layer, however, these read to users that rely on audio feedback as the same i.e. ‘?’. The ‘?’ links did not contain any text that could be relayed to screen reader users.
These icons were changed to "information" icons and the `aria-label` attribute was added:
**Before**:
**After**:
The "Adviser qualifications" icon would link to a different page with information. To keep a consistent behaviour between information icons, now it includes a text with a link to the page:
Issues ID: DAC_TECH_Links_Issue1, DAC-USER-SRNVDA-T2-01, DAC-USER-SRJAWS-T2-02
**Pending**
Copy review for the link's text and Welsh translation.

[DEV APPROVED] 7960 - Add aria-label to information links for screen readers and change their behaviour

---

app/controllers/firms_controller.rb
app/presenters/firm_profile_presenter.rb
app/views/firms/partials/_advice_type_section.html.erb
app/views/firms/partials/_profile_help.html.erb
app/views/firms/show.html.erb
config/locales/cy.yml
config/locales/en.yml
package.json
spec/features/firm_profile_help_spec.rb
spec/fixtures/vcr_cassettes/Help_section_on_a_firm_profile/viewing_information_on_face_to_face_firm.yml
spec/fixtures/vcr_cassettes/Help_section_on_a_firm_profile/viewing_information_on_remote_only_firm.yml
spec/presenters/firm_profile_presenter_spec.rb
spec/support/profile_page.rb

https://moneyadviceservice.tpondemand.com/entity/8587
This ticket addresses the dialogue shown on a firms profile page, regardless of which search a user used to arrive at the profile.
If the firm offers face to face consultation then the message provided will reflect this.
If the firm *only* offers remote consultation then the message will reflect this.

[DEV APPROVED] TP-8587 display correct dialogue

---

app/helpers/application_helper.rb
app/views/layouts/application.html.erb
spec/helpers/application_helper_spec.rb

As of sprockets v3 Rails.application.assets is no longer defined in production. (github issue). 
The purpose of this line is to read the contents of a raw file in dough and then inject the link to that file straight into the view.

[DEV APPROVED] Updates modernizr include to handle Sprockets upgrade from 2 to 3

---

.bowerrc

This fixes a problem with deploying to Staging. 
We need to point to a new Bower registry for reasons of legacy versions.

Updates .bowerrc file to add ref to bower registry

---

app/helpers/office_helper.rb
app/views/firms/partials/_offices.html.erb
spec/helpers/office_helper_spec.rb

Relates to: [TP Card ](https://moneyadviceservice.tpondemand.com/entity/9599-rad-convert-office-url-to-absolute)
I have overlooked the second requirement in the ticket, which asks for the link to open in a new window.
- While doing a sanity test I have discovered
that URI breaks if given a string with lingering spaces. i.e:
'www.somewhere.com '

[DEV APPROVED] [9599] Open office website URL in a new window

---

app/controllers/helpers/search_controller.rb
app/controllers/search_controller.rb
app/views/firms/show.html.erb
config/initializers/geocoder.rb
lib/session_jar.rb
spec/features/landing_face_to_face_search_spec.rb
spec/features/results_face_to_face_search_spec.rb
spec/fixtures/vcr_cassettes/landing_face_to_face_search.yml
spec/lib/session_jar_spec.rb

[TP Card](https://moneyadviceservice.tpondemand.com/entity/9337-rad-back-to-results-to-return)
- In the current implementation the last visited page is not memoized and the user, when clicking 'Back to results' after viewing a Firm's profile is always taken to the first page (if the search is paginated)
- More info in each commit
- The last visited page is now saved in the session, allowing the link to redirect to the latest visited page. 
- The link now does not appear if the user landed on the Firm's profile externally (not from a paginated search)
- Some considerations as the previous VCR cassettes were recorded in 2015, when the API behaved differently and requests could be made without a key (apparently). I have kept the same behaviour (recording cassettes and removing the key form …

[DEV APPROVED] 9337 Back to results to return to last visited page

---

Gemfile
Gemfile.lock
app/views/firms/partials/_content.html.erb
app/views/firms/partials/_firm_details.html.erb
config/initializers/geocoder.rb

[TP 9300](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiRkRBMzk3RTBGNjU3NDg1RDM4QzczMTJFNzI5MDFBN0MifQ==&searchPopup=bug/9300)
The offices tab and location map are only displaying for results returned by `In Person` searches. This tab should be displayed for all search options, `Phone or Online` and `Search for a firm by name`. 
The views use a conditional that checks if the search was a `face to face` search to determine if the offices tab and location map should be displayed. I have removed the conditional.

[DEV APPROVED] BUG: Display office tab for search results

---

app/services/helpers/params_parser.rb
features/cassettes/algolia/firm-profile/view-general-firm-information/post/1/indexes/firm-advisers-test/query.yml
features/cassettes/algolia/firm-profile/view-general-firm-information/post/1/indexes/firm-offices-test/query.yml
features/cassettes/algolia/firm-profile/viewing-multiple-firm-profiles/post/1/indexes/firm-advisers-test/query.yml
features/cassettes/algolia/firm-profile/viewing-multiple-firm-profiles/post/1/indexes/firm-offices-test/query.yml
spec/services/helpers/params_parser_spec.rb
spec/services/search_firms_spec.rb

This PR is fixing a minor bug when geocoding the closest adviser distance on a firm's profile.
In short: a redundant second geocoding using empty coordinates happens when no postcode is provided (i.e. from the search by postcode), resulting in otherwise displaying that the closest adviser is somewhere in the middle of UK.
More info in the card: [TP10546](https://moneyadviceservice.tpondemand.com/entity/10546-rad-adviser-distance-inadequate-in-search) and the commit.

10546 - Fix bogus geocoding bug in profile

---

app/views/contact_methods/_webchat.html.erb
config/locales/cy.yml
config/locales/en.yml

[TP 10579](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiRkRBMzk3RTBGNjU3NDg1RDM4QzczMTJFNzI5MDFBN0MifQ==&boardPopup=bug/10579/silent)
Change the opening hours for webchat and contact by phone to be consistent with the MAS site.

[DEV APPROVED] TP 10579 Amend contact times

---

app/helpers/office_helper.rb
app/views/firms/partials/_header.html.erb
spec/helpers/office_helper_spec.rb

[TP card](https://moneyadviceservice.tpondemand.com/entity/10618-rad-nearest-office-phone-number-to)
On a firm's profile, display phone number belonging to the nearest office, when performing a postcode search

[DEV APPROVED] Show nearest office telephone number on firm profile

---

app/assets/stylesheets/layouts/_office.scss

[TP10843](https://maps.tpondemand.com/entity/10843-rad-large-icons-showing-up-on)
This work addresses a fault that has developed with the display of some icons on the "Offices" panel of an advisor's profile page. This has occurred because some styles relating to these elements were removed as part of an earlier piece of work. This PR restores the removed styles. 
Current: 
Fixed:

Restores deleted styles

---

app/forms/search_form.rb
spec/forms/search_form_spec.rb
spec/support/feature_spec_helper.rb
spec/support/in_person_section.rb
spec/support/remote_section.rb
spec/support/search_criteria_section.rb
spec/support/search_form_section.rb

[TP](https://maps.tpondemand.com/restui/board.aspx?#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiMTc4RkJENkI4OEUyMjA0MjI2RTM2NTMxOEZFNEFDMEIifQ==&boardPopup=bug/10960/silent)
The search filter pension_pot_size is no longer exists and appears to be renamed
into investment_size. Remaining references to pension_pot_size seems to be
leftovers.
This commit removes any reference of the pension_pot_size and gracefully removes
any unsupported params from search request in order not to raise exceptions.

#10960 RAD Consumer: pension_pot_size error in search results

---

app/views/contact_methods/_webchat.html.erb
app/views/contact_methods/_whatsapp.html.erb
bower.json.erb
config/locales/cy.yml
config/locales/en.yml

[TP11052](https://maps.tpondemand.com/entity/11052-add-only-available-in-english-to)
This is the equivalent ticket in RAD to [TP10734](https://maps.tpondemand.com/entity/10734-relocate-the-only-available-in-english) in Frontend. 
The main difference is that the footer is not CMS-controlled in RAD as it is in frontend so the text is added to the codebase. 
Although this text is only required to be rendered to Welsh language users I have added the English equivalent to the translation file to avoid any potential problems with blank values in the file. The text is nonetheless hidden by the CSS for English language users. 
There are no styles added in this PR since these are shared with Frontend via Yeast. 
**Current**
**Updated**

[DEV APPROVED] Adds smallprint to footer for Welsh language users

---

Gemfile
app/assets/javascripts/require_config.js.erb
app/assets/stylesheets/components/_covid_banner.scss
app/assets/stylesheets/shared/_enhanced.scss
app/controllers/application_controller.rb
app/views/application/_covid_banner.erb
app/views/layouts/application.html.erb
app/views/shared/svg/_icon_sprite.html.erb
bower.json.erb
config/locales/cy.yml
config/locales/en.yml

[TP11364](https://maps.tpondemand.com/entity/11364-sticky-banner-on-rad-website-for)
This work implements the Coronavirus banner on RAD. This repeats the task from frontend in [TP11363](https://maps.tpondemand.com/entity/11363-sticky-banner-on-mas-website-for) and should match this exactly for look and feel and for functionality with a couple of exceptions: 
- There is no WhatsApp button on RAD so the width of the banner remains constant. 
- There is no "Back to Top" functionality on long pages so no requirement to dynamically change the position of the banner in response to this element. 
The Dough component is re-used here with no changes. 
The Yeast styles are used here with no changes, though there is an extra style added in RAD to over-ride the width in smaller viewports (as …

[DEV APPROVED] 11364 coronavirus banner

---

Gemfile
Gemfile.lock
app/assets/javascripts/require_config.js.erb
app/views/layouts/application.html.erb

[TP-12564](https://maps.tpondemand.com/entity/12564-rad-scrolling-issue-on-firms-on)
This work implements the existing `PostMessages` Dough component on this repo. It adds a method to send a message from the iFrame to the parent when a change is detected in the body size of the document so that the iFrame height can be adjusted to fit the resized content. 
The component was updated in [PR345](https://github.com/moneyadviceservice/dough/pull/345) on Dough.

12564 scroll i os

---

app/views/contact_methods/_call_us.html.erb
app/views/firms/partials/_firm_links.html.erb
app/views/firms/partials/_offices.html.erb

Turns out these fail when embedded in iframes unless the target is
explicitly set.

Target `mailto` and `tel` protocol links

---

config/routes.rb
lib/mas_redirect_constraints.rb
spec/requests/legacy_redirect_spec.rb

When requests are made with the legacy host
`directory.moneyadviceservice.org.uk` the application will redirect to
the new AEM page, with the correct embed.

Legacy redirects to new AEM embeds

---

lib/tasks/sessions.rake

This grows unbounded and in production there are more than 2.5m rows
that have been redundant for years.

Add a rake task to cleanup stale sessions

---

app/helpers/search_helper.rb
config/locales/en.yml

These are causing issues with 'jump links' and scrolling after the
resize component kicks in so for now we can remove the anchor element
and at least have them functioning.

Remove anchors from glossary links

---

app/views/firms/partials/_advisers.html.erb

There is a weird issue with jumplinks and how href attributes are
parsed and this causes some issues with links and buttons bound in
javascript. Removing the redundant attribute content resolves the issue
for now.

Remove href anchor

---

app/forms/filters/advice_method.rb
features/cassettes/algolia/firm-profile/viewing-a-firm-profile-following-search-in-person-results/post/1/indexes/firm-advisers-test/query.yml
features/cassettes/google/maps/api/geocode/json/address_5B_5D_EC1N2TD_2C_United_Kingdom_language_5B_5D_en_sensor_5B_5D_false.yml
features/cassettes/google/maps/api/geocode/json/address_5B_5D_EC4A2AH_2C_United_Kingdom_language_5B_5D_en_sensor_5B_5D_false.yml
features/firm_profile.feature
spec/fixtures/vcr_cassettes/geocoded_postcode.yml
spec/fixtures/vcr_cassettes/search_in_person_failed_geocode.yml
spec/fixtures/vcr_cassettes/search_in_person_valid_geocode.yml
spec/forms/search_form_spec.rb

Strips whitespace from a postcode before attempting to geocode. Does not alter the presented postcode apart from upcasing.

Strip useless whitespace from postcode

---

config/locales/cy.yml
config/locales/en.yml
features/search_filters.feature
spec/forms/search_form_spec.rb

This is temporarily being placed on hold so we can remove it from filters and glossaries.

Remove Pension Transfer Gold Standard

---

app/views/firms/partials/_offices.html.erb

This doesn't expand into further offices due to a jquery oddity with a blank anchor reference.

Resolve issue with "Show more offices" link
